import { GoogleGenAI } from "@google/genai";

const apiKey = process.env.REACT_APP_GEMINI_API_KEY;
const genAi = new GoogleGenAI({ apiKey });

export async function analyzeContent(content) {
  const prompt = `
    You are an AI text analysis tool. Analyze the following text and determine the likelihood of it being written by a human or generated by AI.

    Provide your output strictly in JSON format with the following structure:

    {
        "ai_percentage": "<number between 0 and 100>",
        "human_percentage": "<number between 0 and 100>",
        "interpretation": "<brief interpretation not exceeding 200 characters>",
        "classification": "<choose one: Extreme Dependence | High Dependence | Moderate Dependence | Low Dependence | Negligible Dependence>",
        "message": "<short explanation of the classification not exceeding 200 characters>"
    }

    Rules:
    - The AI and Human percentages must total 100.
    - Base the classification on the AI percentage:
      - Extreme Dependence: 80–100% AI
      - High Dependence: 60–79% AI
      - Moderate Dependence: 40–59% AI
      - Low Dependence: 20–39% AI
      - Negligible Dependence: 0–19% AI
    - Be concise and factual.
    - Do not include any extra text, markdown, or commentary outside the JSON.

    Text to analyze:
    """
    ${content}
    """
  `;

  const response = await genAi.models.generateContent({
    model: "gemini-2.5-flash",
    contents: [{ parts: [{ text: prompt }] }],
  });

  if (!response.candidates?.[0]?.content?.parts?.[0]?.text) {
    console.error("Empty response from Gemini:", response);
    throw new Error("Empty response from Gemini");
  }

  let textOutput = response.candidates[0].content.parts[0].text;

  // Clean up the text: remove code block markers and trim whitespace
  textOutput = textOutput.replace(/```json\n?/, '').replace(/\n?```$/, '').trim();

  console.log("Raw Gemini output:", textOutput);

  // ✅ Parse safely
  let json;
  try {
    json = JSON.parse(textOutput);
  } catch (err) {
    console.error("Failed to parse Gemini output:", err);
    throw new Error("Gemini returned invalid JSON");
  }

  return json;
}
